name: Build Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test-keyboard-with-advertisement:
    runs-on: ubuntu-latest
    name: Test Keyboard with Advertisement
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: prospector-zmk-module

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('prospector-zmk-module/test/advertisement_test/config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l prospector-zmk-module/test/advertisement_test/config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (Corne with Advertisement)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="$GITHUB_WORKSPACE/prospector-zmk-module/test/advertisement_test/config"

  test-scanner-mode:
    runs-on: ubuntu-latest
    name: Test Prospector Scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: prospector-zmk-module

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('prospector-zmk-module/test/scanner_build_test/config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l prospector-zmk-module/test/scanner_build_test/config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (Prospector Scanner)
        run: west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=prospector_scanner -DZMK_CONFIG="$GITHUB_WORKSPACE/prospector-zmk-module/test/scanner_build_test/config"